import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "../sections/NavBar";
import Footer from "../sections/Footer";
import Container from "@mui/material/Container";

import "./page.module.css";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Container maxWidth="lg">
        <body className={roboto.className}>
          <Navbar />
          {children}
          <Footer />
        </body>
      </Container>
    </html>
  );
}
